//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinaqStorage.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LinaqStorage.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not open this file..
        /// </summary>
        internal static string CantOpenFile {
            get {
                return ResourceManager.GetString("CantOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption Date.
        /// </summary>
        internal static string EncryptDate {
            get {
                return ResourceManager.GetString("EncryptDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption Method.
        /// </summary>
        internal static string EncryptMethod {
            get {
                return ResourceManager.GetString("EncryptMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Extension.
        /// </summary>
        internal static string FileExt {
            get {
                return ResourceManager.GetString("FileExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginPage_Login {
            get {
                return ResourceManager.GetString("LoginPage_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in all fields..
        /// </summary>
        internal static string Message_FilleAllFields {
            get {
                return ResourceManager.GetString("Message_FilleAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login error..
        /// </summary>
        internal static string Message_LoginError {
            get {
                return ResourceManager.GetString("Message_LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password can not be the same as old one..
        /// </summary>
        internal static string Message_NewPasswordCantBeSame {
            get {
                return ResourceManager.GetString("Message_NewPasswordCantBeSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password doesnt match..
        /// </summary>
        internal static string Message_OldPasswordDoesntMatch {
            get {
                return ResourceManager.GetString("Message_OldPasswordDoesntMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least 1 big letter..
        /// </summary>
        internal static string Message_PasswordOneBigLetter {
            get {
                return ResourceManager.GetString("Message_PasswordOneBigLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least 1 number..
        /// </summary>
        internal static string Message_PasswordOneNumber {
            get {
                return ResourceManager.GetString("Message_PasswordOneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least 1 symbol..
        /// </summary>
        internal static string Message_PasswordOneSymbol {
            get {
                return ResourceManager.GetString("Message_PasswordOneSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided passwords doesnt match..
        /// </summary>
        internal static string Message_PasswordsDoesntMatch {
            get {
                return ResourceManager.GetString("Message_PasswordsDoesntMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least 8 characters..
        /// </summary>
        internal static string Message_PasswordTooShort {
            get {
                return ResourceManager.GetString("Message_PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided password is incorrect..
        /// </summary>
        internal static string Message_WrongPassword {
            get {
                return ResourceManager.GetString("Message_WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password.
        /// </summary>
        internal static string Message_WrongPasswrdShort {
            get {
                return ResourceManager.GetString("Message_WrongPasswrdShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string NavigationBar_Contact {
            get {
                return ResourceManager.GetString("NavigationBar_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string NavigationBar_Settings {
            get {
                return ResourceManager.GetString("NavigationBar_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string PasswordPage_ChangePassword {
            get {
                return ResourceManager.GetString("PasswordPage_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        internal static string PasswordPage_ConfirmNewPassword {
            get {
                return ResourceManager.GetString("PasswordPage_ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string PasswordPage_NewPassword {
            get {
                return ResourceManager.GetString("PasswordPage_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        internal static string PasswordPage_OldPassword {
            get {
                return ResourceManager.GetString("PasswordPage_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset.
        /// </summary>
        internal static string PasswordPage_PasswordReset {
            get {
                return ResourceManager.GetString("PasswordPage_PasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password reset operation will result in the loss of all data..
        /// </summary>
        internal static string PasswordPage_PasswordResetInfoLoseData {
            get {
                return ResourceManager.GetString("PasswordPage_PasswordResetInfoLoseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reseted sucessfully.
        /// </summary>
        internal static string PasswordPage_PasswordResetSucessfully {
            get {
                return ResourceManager.GetString("PasswordPage_PasswordResetSucessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string PasswordPage_ResetPassword {
            get {
                return ResourceManager.GetString("PasswordPage_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Password.
        /// </summary>
        internal static string PasswordPage_SavePassword {
            get {
                return ResourceManager.GetString("PasswordPage_SavePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save_as {
            get {
                return ResourceManager.GetString("Save_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string SettingsPage_Browse {
            get {
                return ResourceManager.GetString("SettingsPage_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string SettingsPage_ChangePassword {
            get {
                return ResourceManager.GetString("SettingsPage_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete orignal file after encryption.
        /// </summary>
        internal static string SettingsPage_DeleteOriginalFile {
            get {
                return ResourceManager.GetString("SettingsPage_DeleteOriginalFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption method.
        /// </summary>
        internal static string SettingsPage_EncryptionMethod {
            get {
                return ResourceManager.GetString("SettingsPage_EncryptionMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string SettingsPage_Language {
            get {
                return ResourceManager.GetString("SettingsPage_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string SettingsPage_Password {
            get {
                return ResourceManager.GetString("SettingsPage_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder.
        /// </summary>
        internal static string SettingsPage_SelectFolder {
            get {
                return ResourceManager.GetString("SettingsPage_SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage path.
        /// </summary>
        internal static string SettingsPage_StoragePath {
            get {
                return ResourceManager.GetString("SettingsPage_StoragePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use RSA to encrypt key..
        /// </summary>
        internal static string SettingsPage_UseRSA {
            get {
                return ResourceManager.GetString("SettingsPage_UseRSA", resourceCulture);
            }
        }
    }
}
